name: coverage
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests.yml
          workflow_conclusion: success

      - name: List artifacts
        run: ls -R

      - name: Create Badge
        run: |
          COVERAGE=`cat "./code-coverage-summary/final.txt" | head -1`
          echo "::set-output name=coverage::$COVERAGE"
          if [[ $COVERAGE > 80 ]]
          then
          echo '::set-output name=SELECTED_COLOR::green'
          else if [[ $COVERAGE > 65 ]]
          then
          echo '::set-output name=SELECTED_COLOR::yellow'
          else
          echo '::set-output name=SELECTED_COLOR::red'
          fi
          fi
