name: coverage
on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
      - run: git branch

      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: tests.yml
          workflow_conclusion: success

      - name: List artifacts
        run: ls -R

      - name: Create Badge
        run: |
          COVERAGE=`cat "./code-coverage-summary/final.txt" | head -1`
          echo "::set-output name=coverage::$COVERAGE"
          if [[ $COVERAGE > 80 ]]
          then
          echo "action_state=green" >> $GITHUB_ENV
          else if [[ $COVERAGE > 50 ]]
          then
          echo "action_state=yellow" >> $GITHUB_ENV
          else
          echo "action_state=red" >> $GITHUB_ENV
          fi
          fi
