name: coverage
on:
  workflow_run:
    workflows: ["Node.js CI"]
    types:
      - completed
      - requested

jobs:
  cover:
    name: Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Download coverage
        uses: actions/download-artifact@v2
        with:
          name: code-coverage-report
          path: ./

      - name: Create Badge
        run: |
          COVERAGE=`cat "./final.txt" | head -1`
          echo "::set-output name=coverage::$COVERAGE"
          if [[ $COVERAGE > 80 ]]
          then
          echo '::set-output name=SELECTED_COLOR::green'
          else if [[ $COVERAGE > 65 ]]
          then
          echo '::set-output name=SELECTED_COLOR::yellow'
          else
          echo '::set-output name=SELECTED_COLOR::red'
          fi
          fi
